ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE PLUGGABLE DATABASE PDBQLDH
ADMIN USER pdb_admin IDENTIFIED BY 123
ROLES = (DBA)
FILE_NAME_CONVERT = ('D:\Setup\Oracle\oradata\',
                     'D:\Setup\Oracle\oradata\PDBQLDH');

--ALTER PLUGGABLE DATABASE PDBQLDH CLOSE IMMEDIATE INSTANCES=ALL;
--DROP PLUGGABLE DATABASE PDBQLDH INCLUDING DATAFILES;

ALTER PLUGGABLE DATABASE PDBQLDH OPEN READ WRITE; 
ALTER SESSION SET CONTAINER= PDBQLDH;   
GRANT SYSDBA TO pdb_admin;

-- 3. Tạo user ADMIN01
CREATE USER ADMIN01 IDENTIFIED BY 123;

GRANT SELECT ON DBA_ROLES TO ADMIN01;
GRANT SELECT ON DBA_ROLE_PRIVS TO ADMIN01;

GRANT SYSDBA TO ADMIN01

BEGIN
   EXECUTE IMMEDIATE 'DROP ROLE ADMIN_ROLE';
EXCEPTION
   WHEN OTHERS THEN
      -- ORA-01919: role does not exist
      IF SQLCODE != -01919 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE ROLE ADMIN_ROLE';
END;
/

GRANT CREATE SESSION, RESTRICTED SESSION TO ADMIN_ROLE;
GRANT CONNECT, RESOURCE TO ADMIN_ROLE;
GRANT UNLIMITED TABLESPACE TO ADMIN_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON QLDH_ADMIN TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLDH_NHANVIEN TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLDH_SINHVIEN TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLDH_DONVI TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLDH_HOCPHAN TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLDH_MONHOC TO ADMIN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLDH_DANGKY TO ADMIN_ROLE;

GRANT DROP USER, CREATE USER TO ADMIN_ROLE;

GRANT ADMIN_ROLE TO ADMIN01;

CREATE TABLE QLDH_ADMIN(
    MAAD VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI VARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nu')),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    DT VARCHAR2(15)
);

INSERT INTO QLDH_ADMIN (MAAD, HOTEN, PHAI, NGSINH, DCHI, DT)
VALUES ('ADMIN01', 'Nguyen Van Admin', 'Nam', TO_DATE('01-01-1980', 'DD-MM-YYYY'), 'Hà Nội', '0987654321');

COMMIT;

--Tạo bảng ĐONVI
CREATE TABLE QLDH_DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(50) NOT NULL,
    LOAIDV VARCHAR2(10) CHECK (LOAIDV IN ('Khoa', 'Phong')),
    TRGDV VARCHAR2(10)
);

--Tạo bảng NHANVIEN
CREATE TABLE QLDH_NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI VARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nu')),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    LUONG NUMBER(15,2),
    PHUCAP NUMBER(15,2),
    DT VARCHAR2(15),
    VAITRO VARCHAR2(30) CHECK (VAITRO IN ('NVCB', 'GV', 'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGĐV')),
    MADV VARCHAR2(10),
    CONSTRAINT FK_NV_MADV FOREIGN KEY (MADV) REFERENCES QLDH_DONVI(MADV)
);

--Thêm khóa ngoại TRGDV vào bảng DONVI
ALTER TABLE QLDH_DONVI
ADD CONSTRAINT FK_TRGDV FOREIGN KEY (TRGDV) REFERENCES QLDH_NHANVIEN(MANV);
--Tạo bảng SINHVIEN
CREATE TABLE QLDH_SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI VARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nu')),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    DT VARCHAR2(15),
    KHOA VARCHAR2(10),
    TINHTRANG VARCHAR2(20) CHECK (TINHTRANG IN ('Dang hoc', 'Nghi hoc', 'Bao luu')),
    CONSTRAINT FK_SV_KHOA FOREIGN KEY (KHOA) REFERENCES QLDH_DONVI(MADV)
);
--Tạo bảng HOCPHAN
CREATE TABLE QLDH_HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(50) NOT NULL,
    SOTC NUMBER(2),
    STLT NUMBER(3),
    STTH NUMBER(3),
    MADV VARCHAR2(10),
    FOREIGN KEY (MADV) REFERENCES QLDH_DONVI(MADV)
);
--Tạo bảng MOMON
CREATE TABLE QLDH_MONHOC (
    MAMH VARCHAR2(10) PRIMARY KEY,
    MAHP VARCHAR2(10),
    MAGV VARCHAR2(10),
    HK NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM NUMBER(4),
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE,
    FOREIGN KEY (MAHP) REFERENCES QLDH_HOCPHAN(MAHP),
    FOREIGN KEY (MAGV) REFERENCES QLDH_NHANVIEN(MANV)
);
--Tạo bảng DANGKY
CREATE TABLE QLDH_DANGKY (
    MASV VARCHAR2(10),
    MAMH VARCHAR2(10),
    DIEMTH NUMBER(4,2),
    DIEMQT NUMBER(4,2),
    DIEMCK NUMBER(4,2),
    DIEMTK NUMBER(4,2),
    NGAYDK DATE,
    PRIMARY KEY (MASV, MAMH),
    FOREIGN KEY (MASV) REFERENCES QLDH_SINHVIEN(MASV),
    FOREIGN KEY (MAMH) REFERENCES QLDH_MONHOC(MAMH)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.QLDH_ADMIN TO pdb_admin WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.QLDH_DONVI TO pdb_admin WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.QLDH_NHANVIEN TO pdb_admin WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.QLDH_SINHVIEN TO pdb_admin WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.QLDH_HOCPHAN TO pdb_admin WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.QLDH_MONHOC TO pdb_admin WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.QLDH_DANGKY TO pdb_admin WITH GRANT OPTION;

----------------------------------------------------------------------------------------
-- Thêm giá trị cho DonVi
INSERT INTO QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('KH01', 'Khoa Công nghệ thông tin', 'Khoa', NULL);
INSERT INTO QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('KH02', 'Khoa Kinh tế', 'Khoa',NULL);
INSERT INTO QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('KH03', 'Khoa Ngoại ngữ', 'Khoa', NULL);
INSERT INTO QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PH01', 'Phòng Khảo Thí', 'Phong', NULL);
INSERT INTO QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PH02', 'Phòng Đào tạo', 'Phong', NULL);
