ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE PLUGGABLE DATABASE PDBQLDH
ADMIN USER pdb_admin IDENTIFIED BY 123
ROLES = (DBA)
FILE_NAME_CONVERT = ('C:\app\LK47\product\21c\oradata\XE',
                     'C:\app\LK47\product\21c\oradata\XE\PDBQLDH');

GRANT SYSDBA TO pdb_admin;
ALTER PLUGGABLE DATABASE PDBQLDH OPEN READ WRITE; 
ALTER SESSION SET CONTAINER= PDBQLDH;   
ALTER SESSION SET CURRENT_SCHEMA = pdb_admin;
GRANT DBA TO pdb_admin

CREATE TABLE QLDH_ADMIN(
    MAAD VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI VARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nu')),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    DT VARCHAR2(15)
);

INSERT INTO QLDH_ADMIN (MAAD, HOTEN, PHAI, NGSINH, DCHI, DT)
VALUES ('PDB_ADMIN', 'Nguyen Van Admin', 'Nam', TO_DATE('01-01-1980', 'DD-MM-YYYY'), 'Hà Nội', '0987654321');

--Tạo bảng ĐONVI
CREATE TABLE QLDH_DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(50) NOT NULL,
    LOAIDV VARCHAR2(10) CHECK (LOAIDV IN ('Khoa', 'Phong')),
    TRGDV VARCHAR2(10)
);

SELECT MASV, HOTEN, PHAI, NGSINH, DCHI, DT, TINHTRANG, TENDV
                   FROM PDB_ADMIN.QLDH_SINHVIEN SV
                   JOIN PDB_ADMIN.QLDH_DONVI DV ON SV.KHOA = DV.MADV
                   WHERE SV.MASV = 'KHANHNV3';

--Tạo bảng NHANVIEN
CREATE TABLE QLDH_NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI VARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nu')),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    LUONG NUMBER(15,2),
    PHUCAP NUMBER(15,2),
    DT VARCHAR2(15),
    VAITRO VARCHAR2(30) CHECK (VAITRO IN ('NVCB', 'GV', 'NV PĐT', 'NV PKT', 'NV TCHC', 'NV CTSV', 'TRGĐV')),
    MADV VARCHAR2(10),
    CONSTRAINT FK_NV_MADV FOREIGN KEY (MADV) REFERENCES QLDH_DONVI(MADV)
);

--Thêm khóa ngoại TRGDV vào bảng DONVI
ALTER TABLE QLDH_DONVI
ADD CONSTRAINT FK_TRGDV FOREIGN KEY (TRGDV) REFERENCES QLDH_NHANVIEN(MANV);
--Tạo bảng SINHVIEN
CREATE TABLE QLDH_SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI VARCHAR2(3) CHECK (PHAI IN ('Nam', 'Nu')),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    DT VARCHAR2(15),
    KHOA VARCHAR2(10),
    TINHTRANG VARCHAR2(20) CHECK (TINHTRANG IN ('Dang hoc', 'Nghi hoc', 'Bao luu')),
    CONSTRAINT FK_SV_KHOA FOREIGN KEY (KHOA) REFERENCES QLDH_DONVI(MADV)
);
--Tạo bảng HOCPHAN
CREATE TABLE QLDH_HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(50) NOT NULL,
    SOTC NUMBER(2),
    STLT NUMBER(3),
    STTH NUMBER(3),
    MADV VARCHAR2(10),
    FOREIGN KEY (MADV) REFERENCES QLDH_DONVI(MADV)
);
--Tạo bảng MOMON
CREATE TABLE QLDH_MONHOC (
    MAMH VARCHAR2(10) PRIMARY KEY,
    MAHP VARCHAR2(10),
    MAGV VARCHAR2(10),
    HK NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM NUMBER(4),
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE,
    FOREIGN KEY (MAHP) REFERENCES QLDH_HOCPHAN(MAHP),
    FOREIGN KEY (MAGV) REFERENCES QLDH_NHANVIEN(MANV)
);
--Tạo bảng DANGKY
CREATE TABLE QLDH_DANGKY (
    MASV VARCHAR2(10),
    MAMH VARCHAR2(10),
    DIEMTH NUMBER(4,2),
    DIEMQT NUMBER(4,2),
    DIEMCK NUMBER(4,2),
    DIEMTK NUMBER(4,2),
    NGAYDK DATE,
    PRIMARY KEY (MASV, MAMH),
    FOREIGN KEY (MASV) REFERENCES QLDH_SINHVIEN(MASV),
    FOREIGN KEY (MAMH) REFERENCES QLDH_MONHOC(MAMH)
);

----------------------------------------------------------------------------------------
-- Thêm giá trị cho DonVi
INSERT INTO pdb_admin.QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('KH01', 'Khoa Công nghệ thông tin', 'Khoa', NULL);
INSERT INTO pdb_admin.QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('KH02', 'Khoa Kinh tế', 'Khoa',NULL);
INSERT INTO pdb_admin.QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('KH03', 'Khoa Ngoại ngữ', 'Khoa', NULL);
INSERT INTO pdb_admin.QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PH01', 'Phòng Khảo Thí', 'Phong', NULL);
INSERT INTO pdb_admin.QLDH_DONVI (MADV, TENDV, LOAIDV, TRGDV) VALUES ('PH02', 'Phòng Đào tạo', 'Phong', NULL);

----------------------------------------
-- Thêm dữ liệu hocphan

INSERT INTO QLDH_HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, MADV)
VALUES ('HP001', 'Lập trình C#', 3, 30, 15, 'KH01');

INSERT INTO QLDH_HOCPHAN (MAHP, TENHP, SOTC, STLT, STTH, MADV)
VALUES ('HP002', 'Cơ sở dữ liệu', 4, 40, 20, 'KH01');
 
-- Môn học đang mở
INSERT INTO QLDH_MONHOC (MAMH, MAHP, MAGV, HK, NAM, NGAYBATDAU, NGAYKETTHUC)
VALUES ('MH001', 'HP001', 'KHANHNV2', 2, 2025, SYSDATE - 10, SYSDATE + 20);

-- Môn học đã kết thúc
INSERT INTO QLDH_MONHOC (MAMH, MAHP, MAGV, HK, NAM, NGAYBATDAU, NGAYKETTHUC)
VALUES ('MH002', 'HP002', 'KHANHNV2', 1, 2024, TO_DATE('01/01/2024','DD/MM/YYYY'), TO_DATE('01/03/2024','DD/MM/YYYY'));