-- Tạo quyền
ALTER SESSION SET CONTAINER= PDBQLDH; 
ALTER SESSION SET CURRENT_SCHEMA = pdb_admin;

CREATE ROLE NV_NVCB;        -- Nhân viên cơ bản
CREATE ROLE NV_GV;          -- Giảng viên
CREATE ROLE NV_PDT;         -- Nhân viên Phòng Đào tạo
CREATE ROLE NV_PKT;         -- Nhân viên Phòng Khảo thí
CREATE ROLE NV_TCHC;        -- Nhân viên Phòng Tổ chức hành chính
CREATE ROLE NV_CTSV;        -- Nhân viên Phòng Công tác sinh viên
CREATE ROLE NV_TRGDV;       -- Trưởng đơn vị
CREATE ROLE SV;
-- Tạo ROLE mới
CREATE ROLE LOGIN_ROLE;

-- Role: Đọc thông báo
CREATE ROLE READ_NOTICE;

-------------------------------------------------------------------------
-- Phân quyền cho role
-- Role LOGIN
-- Gán quyền cho LOGIN ROLE
GRANT SELECT ON pdb_admin.QLDH_NHANVIEN TO LOGIN_ROLE;
GRANT SELECT ON pdb_admin.QLDH_SINHVIEN TO LOGIN_ROLE;
GRANT RESTRICTED SESSION TO LOGIN_ROLE;
GRANT SELECT ON pdb_admin.QLDH_DONVI TO LOGIN_ROLE;
GRANT UPDATE (DT) ON pdb_admin.QLDH_NHANVIEN TO LOGIN_ROLE;

-------------------------------------------------------------------------
-- Gán quyền cho NV_CB
-- View hiển thị thông tin nhân viên
CREATE OR REPLACE VIEW QLDH_VIEW_EMP_INFO AS
SELECT * FROM QLDH_NHANVIEN 
WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER');

GRANT SELECT, UPDATE(DT) ON QLDH_VIEW_EMP_INFO TO NV_NVCB;

-------------------------------------------------------------------------
-- Gán quyền cho GV
-- View thông tin giảng dạy của giảng viên
CREATE OR REPLACE VIEW QLDH_VIEW_COURSE_INFO_GV AS
SELECT *
FROM pdb_admin.QLDH_MONHOC
WHERE MAGV = SYS_CONTEXT('USERENV','SESSION_USER');

-- View sinh viên của giảng viên
CREATE OR REPLACE VIEW PDB_ADMIN.V_STUDENTS_BY_GV AS
SELECT 
    hp.TENHP, sv.MASV, sv.HOTEN, sv.PHAI, sv.NGSINH, sv.DCHI, sv.DT, sv.TINHTRANG,
    dk.DIEMTH, dk.DIEMQT, dk.DIEMCK, dk.DIEMTK
FROM 
    PDB_ADMIN.QLDH_DANGKY dk
    JOIN PDB_ADMIN.QLDH_SINHVIEN sv ON dk.MASV = sv.MASV
    JOIN PDB_ADMIN.QLDH_MONHOC mh ON dk.MAMH = mh.MAMH
    JOIN PDB_ADMIN.QLDH_HOCPHAN hp ON mh.MAHP = hp.MAHP
    WHERE mh.MAGV = SYS_CONTEXT('USERENV','SESSION_USER');

-- View môn học của giảng viên
CREATE OR REPLACE VIEW PDB_ADMIN.V_MONHOC_BY_GV AS
SELECT
    mh.MAMH, hp.TENHP, hp.SOTC, mh.HK, mh.NAM,
    mh.NGAYBATDAU, mh.NGAYKETTHUC, mh.MAGV
FROM QLDH_MONHOC mh
JOIN QLDH_HOCPHAN hp ON mh.MAHP = hp.MAHP;

-- View lịch giảng dạy
CREATE OR REPLACE VIEW PDB_ADMIN.QLDH_VIEW_SCHEDULES_BY_GV AS
SELECT mh.MAMH, mh.MAHP, hp.TENHP, hp.SOTC, hp.STLT, hp.STTH, mh.HK, TO_CHAR(mh.NAM) || '-' || TO_CHAR(mh.NAM + 1) AS NAMHOC
FROM pdb_admin.QLDH_MONHOC mh JOIN pdb_admin.QLDH_HOCPHAN hp ON mh.MAHP = hp.MAHP
JOIN pdb_admin.QLDH_NHANVIEN nv ON nv.MANV = mh.MAGV
JOIN pdb_admin.QLDH_DONVI dv ON dv.MADV = hp.MADV
WHERE mh.MAGV = SYS_CONTEXT('USERENV','SESSION_USER');

-- View bảng điểm
CREATE OR REPLACE VIEW PDB_ADMIN.QLDH_VIEW_SCOREBOARD AS
SELECT 
    sv.MASV,
    sv.HOTEN,
    dk.DIEMTH,
    dk.DIEMQT,
    dk.DIEMCK,
    dk.DIEMTK,
    mh.MAHP,
    mh.MAGV
FROM PDB_ADMIN.QLDH_SINHVIEN sv
JOIN PDB_ADMIN.QLDH_DANGKY dk ON sv.MASV = dk.MASV
JOIN PDB_ADMIN.QLDH_MONHOC mh ON dk.MAMH = mh.MAMH
WHERE mh.MAGV = SYS_CONTEXT('USERENV','SESSION_USER');

-- Cấp quyền cho role NV_GV
GRANT SELECT ON QLDH_VIEW_COURSE_INFO_GV TO NV_GV;
GRANT SELECT ON V_STUDENTS_BY_GV TO NV_GV;
GRANT SELECT ON V_MONHOC_BY_GV TO NV_GV;
GRANT SELECT ON PDB_ADMIN.QLDH_VIEW_SCHEDULES_BY_GV TO NV_GV;
GRANT SELECT ON PDB_ADMIN.QLDH_VIEW_SCOREBOARD TO NV_GV;
GRANT SELECT ON PDB_ADMIN.QLDH_SINHVIEN TO NV_GV;
GRANT SELECT ON PDB_ADMIN.QLDH_DANGKY TO NV_GV;
GRANT SELECT ON PDB_ADMIN.QLDH_MONHOC TO NV_GV;
GRANT SELECT, UPDATE(DT) ON QLDH_VIEW_EMP_INFO TO NV_GV;

-------------------------------------------------------------------------
-- Gán quyền cho PDT
-- View môn học hiện tại
CREATE OR REPLACE VIEW QLDH_VIEW_COURSE_INFO_NVPDT AS
SELECT * 
FROM pdb_admin.QLDH_MONHOC
WHERE HK = (SELECT CASE 
                   WHEN EXTRACT(MONTH FROM SYSDATE) IN (10, 11, 12, 1) THEN 1
                   WHEN EXTRACT(MONTH FROM SYSDATE) IN (2, 3, 4, 5) THEN 2
                   WHEN EXTRACT(MONTH FROM SYSDATE) IN (7, 8, 9) THEN 3
                   END
            FROM dual)
AND NAM = EXTRACT(YEAR FROM SYSDATE);

-- View môn học
CREATE OR REPLACE VIEW QLDH_VIEW_SUBJECT_PDT AS
SELECT mh.MAMH, mh.MAHP, hp.TENHP, hp.MADV, dv.TENDV, hp.SOTC ,nv.HOTEN, mh.HK, TO_CHAR(mh.NAM) || '-' || TO_CHAR(mh.NAM + 1) AS NAMHOC, mh.NGAYBATDAU, mh.NGAYKETTHUC
FROM pdb_admin.QLDH_MONHOC mh JOIN pdb_admin.QLDH_HOCPHAN hp ON mh.MAHP = hp.MAHP
JOIN pdb_admin.QLDH_NHANVIEN nv ON nv.MANV = mh.MAGV
JOIN pdb_admin.QLDH_DONVI dv ON dv.MADV = hp.MADV
WHERE mh.NGAYBATDAU <= SYSDATE AND mh.NGAYKETTHUC >= SYSDATE;

-- Cấp quyền cho role NV_PDT
GRANT SELECT ON QLDH_VIEW_COURSE_INFO_NVPDT TO NV_PDT;
GRANT SELECT, UPDATE, DELETE, INSERT ON QLDH_MONHOC TO NV_PDT;
GRANT SELECT ON QLDH_HOCPHAN TO NV_PDT;
GRANT SELECT ON QLDH_VIEW_SUBJECT_PDT TO NV_PDT;
GRANT SELECT, UPDATE(TINHTRANG) ON pdb_admin.QLDH_SINHVIEN TO NV_PDT;
GRANT SELECT, UPDATE, DELETE, INSERT ON PDB_ADMIN.QLDH_DANGKY TO NV_PDT;

-------------------------------------------------------------------------
-- Gán quyền cho PKT
-- View tất cả môn học
CREATE OR REPLACE VIEW PDB_ADMIN.QLDH_VIEW_ALL_SUBJECTS AS
SELECT 
    MAHP,
    TENHP
FROM PDB_ADMIN.QLDH_HOCPHAN
ORDER BY MAHP;

-- View bảng điểm tổng hợp
CREATE OR REPLACE VIEW PDB_ADMIN.QLDH_VIEW_SCOREBOARD1 AS
SELECT 
    sv.MASV,
    sv.HOTEN,
    dk.DIEMTH,
    dk.DIEMQT,
    dk.DIEMCK,
    dk.DIEMTK,
    mh.MAHP,
    mh.MAGV,
    mh.MAMH
FROM PDB_ADMIN.QLDH_SINHVIEN sv
JOIN PDB_ADMIN.QLDH_DANGKY dk ON sv.MASV = dk.MASV
JOIN PDB_ADMIN.QLDH_MONHOC mh ON dk.MAMH = mh.MAMH;

-------------------------------------------------------------------------
-- Cấp quyền cho role NV_PKT
GRANT SELECT ON PDB_ADMIN.QLDH_VIEW_ALL_SUBJECTS TO NV_PKT;
GRANT SELECT ON PDB_ADMIN.QLDH_VIEW_SCOREBOARD1 TO NV_PKT;
GRANT SELECT ON PDB_ADMIN.QLDH_SINHVIEN TO NV_PKT;
GRANT SELECT ON PDB_ADMIN.QLDH_HOCPHAN TO NV_PKT;
GRANT SELECT ON PDB_ADMIN.QLDH_DANGKY TO NV_PKT;
GRANT SELECT ON PDB_ADMIN.QLDH_MONHOC TO NV_PKT;
GRANT UPDATE ON PDB_ADMIN.QLDH_DANGKY TO NV_PKT;

-------------------------------------------------------------------------
-- Gán quyền cho role TCHC
GRANT SELECT,INSERT,UPDATE,DELETE ON pdb_admin.QLDH_NHANVIEN TO NV_TCHC;

-------------------------------------------------------------------------
-- Gán quyền cho CTSV
GRANT SELECT, INSERT, UPDATE, DELETE ON PDB_ADMIN.QLDH_SINHVIEN TO NV_CTSV;
GRANT UPDATE ON PDB_ADMIN.QLDH_HOCPHAN TO NV_CTSV;
GRANT UPDATE ON PDB_ADMIN.QLDH_MONHOC TO NV_CTSV;
GRANT SELECT, INSERT, UPDATE, DELETE ON QLDH_MONHOC TO NV_CTSV;
GRANT SELECT ON QLDH_NHANVIEN TO NV_CTSV;
GRANT SELECT ON QLDH_DONVI TO NV_CTSV;
GRANT SELECT ON QLDH_HOCPHAN TO NV_CTSV;
GRANT INSERT, DELETE, UPDATE (MASV, HOTEN, PHAI, NGSINH, DCHI, DT, KHOA) ON QLDH_SINHVIEN TO NV_CTSV;

-------------------------------------------------------------------------
-- Gán quyền cho Trưởng đơn vị
-- View nhân viên thuộc đơn vị
CREATE OR REPLACE VIEW QLDH_VIEW_MANAGER_EMPS AS
SELECT e.MANV, e.HOTEN, e.PHAI, e.NGSINH, e.DT, e.VAITRO, e.MADV
FROM pdb_admin.QLDH_NHANVIEN m 
JOIN pdb_admin.QLDH_DONVI u ON m.MANV = u.TRGDV 
JOIN pdb_admin.QLDH_NHANVIEN e ON u.MADV = e.MADV
WHERE m.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

-- View lịch giảng dạy của đơn vị
CREATE OR REPLACE VIEW PDB_ADMIN.VIEW_SCHEDULE_OF_EMPLOYEES AS
SELECT mh.MAMH, mh.MAHP, hp.TENHP, hp.SOTC, hp.STLT, hp.STTH, mh.HK, TO_CHAR(mh.NAM) || '-' || TO_CHAR(mh.NAM + 1) AS NAMHOC
FROM pdb_admin.QLDH_MONHOC mh JOIN pdb_admin.QLDH_HOCPHAN hp ON mh.MAHP = hp.MAHP
JOIN pdb_admin.QLDH_NHANVIEN nv ON nv.MANV = mh.MAGV
JOIN pdb_admin.QLDH_DONVI dv ON dv.MADV = hp.MADV
WHERE nv.MADV = (
    SELECT p.MADV 
    FROM pdb_admin.QLDH_NHANVIEN p 
    WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER'));

-- View phân công giảng dạy
CREATE OR REPLACE VIEW QLDH_VIEW_COURSE_INFO_TRGDV  AS
SELECT s.MAMH, s.MAHP, s.MAGV,s.HK,s.NAM
FROM pdb_admin.QLDH_MONHOC s 
JOIN pdb_admin.QLDH_NHANVIEN e ON s.MAGV = e.MANV
JOIN pdb_admin.QLDH_DONVI u ON e.MADV = u.MADV
JOIN pdb_admin.QLDH_NHANVIEN m ON m.MANV = u.TRGDV
WHERE m.MANV  = SYS_CONTEXT('USERENV','SESSION_USER');

-------------------------------------------------------------------------
-- Cấp quyền cho role NV_TRGDV
GRANT SELECT ON QLDH_VIEW_MANAGER_EMPS TO NV_TRGDV;
GRANT SELECT ON PDB_ADMIN.VIEW_SCHEDULE_OF_EMPLOYEES TO NV_TRGDV;
GRANT SELECT ON QLDH_VIEW_COURSE_INFO_TRGDV TO NV_TRGDV;
GRANT SELECT, UPDATE(DT) ON QLDH_VIEW_EMP_INFO TO NV_TRGDV;

-------------------------------------------------------------------------
-- Gán quyền cho Sinh VIên
-- View xem thông tin cá nhân
CREATE OR REPLACE VIEW PDB_ADMIN.VIEW_INFO_SV AS
SELECT MASV, HOTEN, PHAI, NGSINH, DCHI, DT, TINHTRANG, TENDV
FROM PDB_ADMIN.QLDH_SINHVIEN SV
JOIN PDB_ADMIN.QLDH_DONVI DV ON SV.KHOA = DV.MADV
WHERE SV.MASV = SYS_CONTEXT('USERENV','SESSION_USER');

CONN SV1/123@LOCALHOST:1521/PDBQLDH
SELECT SYS_CONTEXT('USERENV','SESSION_USER') FROM DUAL;
SELECT * FROM VIEW_INFO_SV;

-- View môn học sinh viên
CREATE OR REPLACE VIEW QLDH_VIEW_COURSE_INFO_SV AS
SELECT sub.MAMH, m.TENHP, m.SOTC, nv.HOTEN, sub.HK,sub.NAM
FROM pdb_admin.QLDH_MONHOC sub
JOIN pdb_admin.QLDH_HOCPHAN m ON sub.MAHP = m.MAHP
JOIN pdb_admin.QLDH_SINHVIEN s ON s.KHOA = m.MADV
JOIN pdb_admin.QLDH_NHANVIEN nv ON sub.MAGV = nv.MANV;

-- View đăng ký môn học
CREATE OR REPLACE VIEW QLDH_VIEW_REGISTERED_INFO_SV AS
SELECT d.MAMH, m.TENHP, m.SOTC, nv.HOTEN AS GIANGVIEN, mh.HK, mh.NAM
FROM pdb_admin.QLDH_DANGKY d
JOIN pdb_admin.QLDH_MONHOC mh ON d.MAMH = mh.MAMH
JOIN pdb_admin.QLDH_HOCPHAN m ON mh.MAHP = m.MAHP
JOIN pdb_admin.QLDH_NHANVIEN nv ON mh.MAGV = nv.MANV
WHERE d.MASV = SYS_CONTEXT('USERENV','SESSION_USER');

-- Cấp quyền cho role SV
GRANT SELECT, UPDATE, DELETE, INSERT ON QLDH_VIEW_COURSE_INFO_SV TO SV;
GRANT SELECT, UPDATE, DELETE, INSERT ON QLDH_VIEW_REGISTERED_INFO_SV TO SV;
GRANT SELECT, UPDATE, DELETE, INSERT ON QLDH_DANGKY TO SV;
GRANT UPDATE (DCHI, DT) ON PDB_ADMIN.QLDH_SINHVIEN TO SV;
GRANT SELECT ON PDB_ADMIN.VIEW_INFO_SV TO SV;

-- Gán quyền cho Role Read-Notice
GRANT SELECT ON QLDH_THONGBAO TO READ_NOTICE;

------------------------------------------------------
-- Procedure quản lý
-- Tạo procedure gán role cho user
CREATE OR REPLACE PROCEDURE GRANT_ROLE_TO_USER (
    p_username IN VARCHAR2,
    p_roles IN VARCHAR2     -- Danh sách các role đã được chọn
)
IS
    v_role VARCHAR2(100);
    v_roles DBMS_UTILITY.lname_array;
    v_count INTEGER;
BEGIN
    -- Tách chuỗi p_roles thành mảng
    DBMS_UTILITY.COMMA_TO_TABLE(p_roles, v_count, v_roles);
    FOR i IN 1 .. v_count LOOP
        EXECUTE IMMEDIATE 'GRANT ' || v_roles(i) || ' TO ' || p_username;
    END LOOP;
END;
/

-- Gán quyền cho Role
CREATE OR REPLACE PROCEDURE GRANT_PRIVS_TO_ROLE (
    v_role IN VARCHAR2,
    v_table IN VARCHAR2,
    v_privs IN VARCHAR2
)
IS
    v_sql VARCHAR2(1000);
BEGIN
    v_sql := 'GRANT ' || v_privs || ' ON ' || v_table || ' TO ' || v_role;
    
    -- Thực thi
    EXECUTE IMMEDIATE v_sql;
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- Thu hồi quyền của role
CREATE OR REPLACE PROCEDURE REVOKE_PRIVS_FROM_ROLE (
    v_role IN VARCHAR2,
    v_table IN VARCHAR2,
    v_privs IN VARCHAR2
)
IS
    v_sql VARCHAR2(1000);
BEGIN
    v_sql := 'REVOKE ' || v_privs || ' ON ' || v_table || ' FROM ' || v_role;
    
    EXECUTE IMMEDIATE v_sql;
    
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- Cấp quyền cho user
CREATE OR REPLACE PROCEDURE GRANT_PRIV_TO_USER (
    v_user IN VARCHAR2,
    v_table IN VARCHAR2,
    v_privs IN VARCHAR2,
    v_grant_option IN BOOLEAN
)
IS
    v_sql VARCHAR2(1000);
BEGIN
    v_sql := 'GRANT ' || v_privs || ' ON ' || v_table || ' TO ' || v_user;
    
    -- Kiểm tra WITH GRANT OPTION
    IF v_grant_option THEN
        v_sql := v_sql || ' WITH GRANT OPTION';
    END IF;
    
    EXECUTE IMMEDIATE v_sql;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, 'Lỗi khi cấp quyền cho user: ' || SQLERRM);
END;
/

-- Thu hồi quyền user
CREATE OR REPLACE PROCEDURE REVOKE_PRIVS_FROM_USER (
    v_username IN VARCHAR2,
    v_table IN VARCHAR2,
    v_privs IN VARCHAR2
)
IS
    v_sql VARCHAR2(1000);
BEGIN
    v_sql := 'REVOKE ' || v_privs || ' ON ' || v_table || ' FROM ' || v_username;
    
    EXECUTE IMMEDIATE v_sql;
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20004, 'Lỗi khi thu hồi quyền: ' || SQLERRM);
END;
/